### ISSUE TITLE
Ready to release v0.1.0

### ISSUE THREAD

**Issue by seopbo** [lassl/lassl#27]
# Summary
기본적으로 전체적인 틀은 잡혀있는 사항 `v0.1.0`을 release하기에 앞서 다음의 내용에 대해서 논의

- `serialize_corpora.py`와 `train_tokenizer.py`가 지원하는 `model_type`에 이격이 존재
  - `serialie_corpora.py`: `roberta`, `gpt2`, `albert`
  - `train_tokenizer.py`: `bert-uncased`, `bert-cased`, `gpt2`, `roberta`, `albert`, `electra`
- `README.md`

**Comment by seopbo** [comment]
# `serialize_corpora.py`와 `train_tokenizer.py`가 지원하는 `model_type`에 이격이 존재
이격을 제거하기위해 일단 `train_tokenizer.py`에서 `electra`를 제거하고, `serialize_corpora.py`에서 `bert`를 지원하면 어떨 지? (즉 `BertProcessor`의 개발이 필요함). 이 작업에서 @monologg 님이 제기하신 이슈에 대한 논의도 이루어지면 좋을 것 같음. (아래를 참고)

- https://github.com/lassl/lassl/pull/26#discussion_r758930963

**Comment by iron-ij** [comment]
`bert`와 `electra`가 동일한 `serialize` 과정을 거치는 것으로 알고있는데, `BertProcessor`를 작업할 계획이라면 굳이 제거할 필요가 없지 않나 싶습니다.

**Comment by seopbo** [comment]
> `bert`와 `electra`가 동일한 `serialize` 과정을 거치는 것으로 알고있는데, `BertProcessor`를 작업할 계획이라면 굳이 제거할 필요가 없지 않나 싶습니다.

음 저는 `bert`의 경우에는 `NSP`나 `SOP` 둘 중에 하나는 들어가야된다고 생각했기때문에, `electra`와는 다르다고 생각했습니다. to: @iron-ij

**Comment by iron-ij** [comment]
@seopbo 
현재 구현체 보면 Processor 쪽에서 serialize하고 collator쪽에서 NSP나 SOP가 들어가는게 자연스러울 것 같은데 그렇게 되면 사실상 변경점이  없을 것 같고 SOP를 쓰는게 좋을듯 하네요.
1안 : electra를 남겨두고 여지를 준다 (단, 이 경우 collator에서 SOP 사용여부를 옵션으로 제공하는게 좋을듯?)
2안 : electra 걍 없애고, SOP적용
써놓고 나니 2안이면 할게 별로 없긴하군요 ㅎㅎ

**Comment by bzantium** [comment]
NSP가 아닌 SOP를 사용할 예정이라면 BertProcessor를 AlbertProcessor를 상속받은 형태로만 작성하면 될 것 같고, 사용여부를 옵션으로 주는 것이 아니라 SOP를 무조건 사용하도록 하는 것이 맞을 것 같습니다. 이 경우 Electra는 원하면 구현하고 (아마도 근데 Electra의 경우 Pretrained BERT가 필요해서 제외하는 게 낫지 않을까 싶습니다만...) 아니면 이번 릴리즈에서는 제외해도 좋을 것 같습니다 :)

**Comment by bzantium** [comment]
@monologg @seopbo NFD normalization을 사용할 경우 한국어 성능에 보통 부정적인 영향을 주나요? 또한 한국어에 대해서는 유니코드 정규화 방법을 적용하지 않는 것이 일반적인 방법인가요?

**Comment by monologg** [comment]
> @monologg @seopbo NFD normalization을 사용할 경우 한국어 성능에 보통 부정적인 영향을 주나요? 또한 한국어에 대해서는 유니코드 정규화 방법을 적용하지 않는 것이 일반적인 방법인가요?

@bzantium 

NFD로 저장되는 대표적인 예가 맥에서 한국어로 된 파일이름을 저장할 때입니다 (ex. `오늘` -> `ㅇㅗㄴㅡㄹ`)
이로 인해 BertTokenizer에서 NFD로 normalize된 단어가 `[UNK]` 으로 처리되는 이슈가 생기게 됩니다 (초창기에 `bert-base-multilingual-uncased`를 한국어에 사용하기 어려웠던 이유가 이에 해당합니다)

아래 두 개의 reference를 읽어보는 것을 추천드립니다:)

- https://gist.github.com/Pusnow/aa865fa21f9557fa58d691a8b79f8a6d
- https://github.com/google-research/bert/pull/228

**Comment by monologg** [comment]
> @monologg @seopbo NFD normalization을 사용할 경우 한국어 성능에 보통 부정적인 영향을 주나요? 또한 한국어에 대해서는 유니코드 정규화 방법을 적용하지 않는 것이 일반적인 방법인가요?

@bzantium @seopbo 

NFD가 성능 자체에 부정적인 영향을 주지 않습니다.
tokenizer를 만들 때도 NFD로 생성되면 큰 문제가 없겠네요.... 해당 이슈는 문제가 없을 것 같습니다! 혼란을 주어서 정말 죄송합니다 🙇

**Comment by seopbo** [comment]
> > @monologg @seopbo NFD normalization을 사용할 경우 한국어 성능에 보통 부정적인 영향을 주나요? 또한 한국어에 대해서는 유니코드 정규화 방법을 적용하지 않는 것이 일반적인 방법인가요?
> 
> @bzantium @seopbo
> 
> NFD가 성능 자체에 부정적인 영향을 주지 않습니다. tokenizer를 만들 때도 NFD로 생성되면 큰 문제가 없겠네요.... 해당 이슈는 문제가 없을 것 같습니다! 혼란을 주어서 정말 죄송합니다 🙇

확인감사합니다. to: @monologg

**Comment by seopbo** [comment]
> NSP가 아닌 SOP를 사용할 예정이라면 BertProcessor를 AlbertProcessor를 상속받은 형태로만 작성하면 될 것 같고, 사용여부를 옵션으로 주는 것이 아니라 SOP를 무조건 사용하도록 하는 것이 맞을 것 같습니다. 이 경우 Electra는 원하면 구현하고 (아마도 근데 Electra의 경우 Pretrained BERT가 필요해서 제외하는 게 낫지 않을까 싶습니다만...) 아니면 이번 릴리즈에서는 제외해도 좋을 것 같습니다 :)

저도 이 의견에 동의합니다. 다만 `NSP`를 구현해보고싶은 욕망도 있긴하군요 ㅋㅋ to: @bzantium

**Comment by seopbo** [comment]
어느 정도 해결되어 close합니다.
