### ISSUE TITLE
Roberta의 special token id 순서

### ISSUE THREAD

**Issue by monologg** [lassl/lassl#28]
## Potential Issue

- 현재 Roberta Tokenizer를 만들 때 아래와 같은 순서로 vocab 앞단에 들어갑니다

https://github.com/lassl/lassl/blob/876b368f6615b1ad98da357ab2a0c81fde0e2097/configs/tokenizer/model/roberta.yaml#L18

- 이로인해 **padding_idx == 3**으로 설정되고 ([관련 코드](https://github.com/huggingface/transformers/blob/b4b562d83415d842c081f571e0ec325f40f276aa/src/transformers/models/roberta/modeling_roberta.py#L97))

- position_ids의 길이가 514가 아닌 **516으로 설정**되는 이슈가 발생합니다. ([관련 코드](https://github.com/huggingface/transformers/blob/b4b562d83415d842c081f571e0ec325f40f276aa/src/transformers/models/roberta/modeling_roberta.py#L154-L156))

## How to?

- **original roberta-base**의 경우 special token의 순서가 아래와 같이 들어갑니다
  - `["<s>", "<pad>", "</s>", "<unk>"]`
  - (roberta vocab이 gpt2 vocab에서 가져온 관계로, mask token이 없는 gpt2 vocab의 맨 끝에 `"<mask>"` 를 추가함)
  - https://huggingface.co/roberta-base/blob/main/vocab.json

- 잠재적인 이슈를 막기 위해 **lassl의 roberta tokenizer도 `["<s>", "<pad>", "</s>", "<unk>"]` 의 순서로 가는 것**이 어떤지 의견 구합니다! 🙇 🙇  (cc. @bzantium )

## 📎 Additional context

- `padding_idx + 1` 로 position_ids가 지정되는 코드
  - [transformers](https://github.com/huggingface/transformers/blob/v4.6.0/src/transformers/models/roberta/modeling_roberta.py#L141) 
  - [fairseq](https://github.com/pytorch/fairseq/blob/ba5f829f64d2adf9de4502dab94abf0a1a54106b/fairseq/utils.py#L168)

**Comment by bzantium** [comment]
완전 이상하네요 `padding_idx + 1` 이라니 그러면 혹시 <mask>를 5번째로 놓는 것은 문제없는것이죠?
`["<s>", "<pad>", "</s>", "<unk>", "<mask>"]` 이렇게요!

**Comment by monologg** [comment]
> 완전 이상하네요 `padding_idx + 1` 이라니 그러면 혹시 `<mask>`를 5번째 special_tokens로 놓는 것은 문제없는것이죠?
> `["<s>", "<pad>", "</s>", "<unk>", "<mask>"]` 이렇게요!

@bzantium 
`<mask>`는 문제가 없을껍니다. (pad_token_idx==1 로 고정만 되면 괜찮을꺼에요ㅎㅎ)
`["<s>", "<pad>", "</s>", "<unk>", "<mask>"]` 로 바꾸면 좋을 것 같습니다!

**Comment by bzantium** [comment]
넵 이부분 반영해서 PR올리도록 하겠습니다!
