### ISSUE TITLE
모두의 원시말뭉치 신청하기

### ISSUE THREAD

**Issue by seopbo** [lassl/lassl#3]

**Comment by bzantium** [comment]
- [x] 문어 말뭉치 (1.0)
- [x] 신문 말뭉치 (2.0)

**Comment by seopbo** [comment]
> * [x]  문어 말뭉치 (1.0)
> * [x]  신문 말뭉치 (2.0)

이거 개별로 다신청해야하는걸까요? 이전에 @monologg 님이 말씀하신 원시말뭉치라는 게 뭔지를 모르겠네요??

**Comment by monologg** [comment]
- 신문말뭉치 2020
- 구어 말뭉치
- 신문말뭉치
- 문어말뭉치

**Comment by monologg** [comment]
옛날에는 대화말뭉치 같은 것도 있었는데 개인정보 이슈로 내렸나보네요....

**Comment by bzantium** [comment]
일단 

> * 신문말뭉치 2020
> * 구어 말뭉치
> * 신문말뭉치
> * 문어말뭉치

일단 언급주신 말뭉치들 신청해놓겠습니당

**Comment by bzantium** [comment]
![image](https://user-images.githubusercontent.com/19511788/144198803-dbb4c50c-8c80-4780-ba3a-07f01ce8a996.png)
데이터 신청 승인 받았습니다. 이제 전처리 조금씩 준비하면 될 것 같아요!

**Comment by seopbo** [comment]
# 학습에 활용
- 구어 말뭉치
- 일상 대화 말뭉치 2020
- 비출판물 말뭉치
- 문어 말뭉치
- 신문 말뭉치
- 신문 말뭉치 2020

cc: @bzantium @monologg @iron-ij
