### ISSUE TITLE
Python Minimum Version

### ISSUE THREAD

**Issue by monologg** [lassl/lassl#30]
## ❓ Question

혹시 lassl에서 지원하려는 **최소 파이썬 버전**이 어떻게 되나요?
3.6 부터 지원한다고 하면 `requirements.txt`에 `dataclasses`를 넣어야 할 것 같아서요!

```text
dataclasses; python_version<"3.7"
```

**Comment by bzantium** [comment]
3.6부터 지원하면 될 것 같습니다. 이슈주신 것과 같이 추가하면 될 것 같네요!

**Comment by monologg** [comment]
PR: #32
