### ISSUE TITLE
Refactor pretrain_language_model.py

### ISSUE THREAD

**Issue by bzantium** [lassl/lassl#30]
# TODO: Collator
- 지원하는 모델이 증가함에 따라 collator 또한 지속적으로 구현해야할 것으로 예상되므로 collator를 각 모델별 이름으로 수정하는 것을 건의함.

**Comment by seopbo** [comment]
저의 의견은 아래와 같습니다.

- `DataCollatorForBert`: whole word masking, sop, mlm
- `DataCollatorForAlbert`: sop, mlm
- `DataCollatorForRoberta`: 기존 `DataCollatorForLanguageModeling`를 상속받아서 함수에 `partial` 쓰듯이 정의
- `DataCollatorForGpt2`: 기존 `DataCollatorForLanguageModeling`를 상속받아서 함수에 `partial` 쓰듯이 정의

cc: @monologg @iron-ij @bzantium @alxiom

**Comment by bzantium** [comment]
저는 보섭님 의견에 동의합니다 :)

**Comment by seopbo** [comment]
# TODO: Eval
`eval_dataset` 관련 코드 추가
