### ISSUE TITLE
Add keep_in_memory option in load_dataset

### ISSUE THREAD

**Issue by iron-ij** [lassl/lassl#42]
**Is your feature request related to a problem? Please describe.**
- TPU VM에서 학습하는 과정에서 캐쉬로 인해 메모리가 충분함에도 disk 용량이 꽉차는 이슈가 발생함

**Describe the solution you'd like**
- load_dataset 단계에서 keep_in_memory 옵션을 추가하여 해결
- Serialize과정이완료된 데이터는 disk에 저장되므로, train 단계에서는 필요가 없고 tokenizer, serialize과정에서만 추가

**Comment by seopbo** [comment]
아래의 경우에 대응되는 지 확인하고 싶습니다.

- `train_tokenizer.py`
  - `load_corpora` 함수는 memory-mapping을 사용하기위해서, `keep_in_memory=False` 상태로만 가동하는 것이 좋아보임.
  - `load_corpora` 함수 내부에서 호출되는 `load_dataset` 함수의 `keep_in_memory`에 대한 설명 (True여도 아래 환경변수가 세팅되어 있어야함.)

  ![image](https://user-images.githubusercontent.com/19755607/144751731-7c220baa-eb89-46e9-bf7c-9ab6053b0dcf.png)

- `serialize_corpora.py`
  - `load_corpora` 함수는 memory-mapping을 사용하기위해서, `keep_in_memory=False` 상태로만 가동하는 것이 좋아보임.
  - `map` 호출 시, `keep_in_memory=False`를 유지하는 것이 좋아보이나 (memory보다 hdd, sdd가 더 큰 상황이 일반적임.), 경우에 따라 `keep_in_memory=True`로 사용할 수 있으면 좋음. 

  ![image](https://user-images.githubusercontent.com/19755607/144751814-3fbac8ce-c3d7-49fa-8ae9-f2e4bcbc7e97.png)


ref: 
- https://huggingface.co/docs/datasets/about_arrow.html#memory-mapping
- https://huggingface.co/docs/datasets/cache.html#improve-performance

to: @iron-ij 
cc: @bzantium @monologg @alxiom

**Comment by iron-ij** [comment]
@seopbo 
위 경우에 대응하려면 `map` 함수에서 `keep_in_memory`를 사용하는 것이 좋을 것 같고요,
그에 따라 util 함수에 있는 `load_corpora` 에서 `keep_in_memory`를 처리하는 것이 아닌 `map`에서 `keep_in_memory` 옵션을 추가하는 것이 좋아 보여요.

pr에는 위 방식으로 가볍게 옵션을 추가하는 방식으로만 반영했습니다.
