### ISSUE TITLE
Support training BART

### ISSUE THREAD

**Issue by bzantium** [lassl/lassl#55]
**Is your feature request related to a problem? Please describe.**
BART processor, collator 추가하기

**Describe the solution you'd like**
text_infilling 방법을 collator로 추가한다.

**Comment by hyunwoongko** [comment]
@seopbo 요거 혹시 진행 되고 있나요?

**Comment by seopbo** [comment]
> @seopbo 요거 혹시 진행 되고 있나요?

현재 진행되고 있지 않은 걸로 알고있습니다. 저는 다음 주에 마지막 출근일이라서 그때부터 액티브하게 기타 이슈들을 처리할 것 같습니다 ㅎㅎ

**Comment by bzantium** [comment]
죄송합니다. 진행을 못하고 있네요...

**Comment by hyunwoongko** [comment]
괜찮으면 이거 저희쪽에서 한번 해보고 컨트리뷰트 하겠습니다. 논의하고 다시 말씀드리겠습니다.
