### ISSUE TITLE
TPU + HF Trainer 정상 동작 체크

### ISSUE THREAD

**Issue by monologg** [lassl/lassl#7]
## TODO

- [x] TPU + HF Trainer 정상 동작 체크
- [x] 각 단계에서의 메모리 사용량 체크

**Comment by monologg** [comment]
~~TPU 안의 torch 기본 버전이 `1.8.1` 로 이에 맞게 requirements 수정 필요~~

**Comment by seopbo** [comment]
> * TPU 안의 torch 기본 버전이 `1.8.1` 로 이에 맞게 requirements 수정 필요

TPU를 사용할 때, 기본적으로 docker image는 어떤 것을 사용하나요?

**Comment by monologg** [comment]
보통 한번 학습하면 다신 사용하지 않는 일시적인 서버이기도 하고 TPU Node 기준으로 conda가 함께 설치되어 있어, 기본 환경 그대로 진행해왔습니다

**Comment by monologg** [comment]
https://github.com/pytorch/xla/releases/tag/v1.10.0

보아하니 huggingface LM 예제도 공식 지원되기도 해서 nightly나 도커 통해서 시도 해볼만할 것 같습니다.

**Comment by monologg** [comment]
제가 얘기한 부분은 TPU Node가 아닌 TPU VM 기준인지라 추가적인 확인을 해봐야할 것 같습니다

- https://github.com/pytorch/xla#-consume-prebuilt-compute-vm-images
- https://cloud.google.com/tpu/docs/pytorch-xla-ug-tpu-vm

**Comment by monologg** [comment]
> * TPU 안의 torch 기본 버전이 `1.8.1` 로 이에 맞게 requirements 수정 필요

정정합니다ㅋㅋㅋ 보니까 VM에 1.10이 기본으로 깔린 이미지가 있네요.

```bash
gcloud alpha compute tpus tpu-vm create $VM_NAME --accelerator-type v3-8 --version tpu-vm-pt-1.10 --zone europe-west4-a
```
![Screenshot_20211123-230304](https://user-images.githubusercontent.com/28896432/143038285-dfc1e8c2-aef2-46b0-84b9-aac670d5cf49.png)

**Comment by seopbo** [comment]
> > * TPU 안의 torch 기본 버전이 `1.8.1` 로 이에 맞게 requirements 수정 필요
> 
> 정정합니다ㅋㅋㅋ 보니까 VM에 1.10이 기본으로 깔린 이미지가 있네요.
> 
> ```shell
> gcloud alpha compute tpus tpu-vm create $VM_NAME --accelerator-type v3-8 --version tpu-vm-pt-1.10 --zone europe-west4-a
> ```
> 
> ![Screenshot_20211123-230304](https://user-images.githubusercontent.com/28896432/143038285-dfc1e8c2-aef2-46b0-84b9-aac670d5cf49.png)

확인 감사합니다. 역시 tpu 고수!
