### ISSUE TITLE
Add UL2 Language Modeling

### ISSUE THREAD

**Issue by DaehanKim** [lassl/lassl#94]
슬랙에서도 소개하긴 했는데 Universal Language Learning Paradigm 논문에 소개된 Mixture of Denoisers 를 활용한 목적함수가 기존 Span corruption, MLM, CLM 보다 전반적으로 좋다고 합니다. 저도 마침 회사에서 활용해 볼 생각이 있어서 lassl에 collator 및 processor를 구현하려고 하는데 어떻게 생각하시나요??

**Comment by seopbo** [comment]
@DaehanKim 답변이 늦어서 죄송합니다. 새로운 모델은 언제나 환영합니다.

![image](https://user-images.githubusercontent.com/19755607/182401092-1cc5db3c-d1c5-4fcf-8d89-7da5db0c6b14.png)

**Comment by DaehanKim** [comment]
@seopbo 한 가지 이슈가 있는데요. 
기존 `train_tokenizers.py`에서 `train_new_from_iterator`함수로 학습하는 경우에는 기존 special token 위치가 고정되고 `additional_special_token` 인자로 받은 추가적인 special token이 뒤쪽에 붙는 방식으로 학습되게 됩니다.
예를 들어 T5 같은 경우 <extra_id_0> 부터 <extra_id_99>까지가 102~3번까지 역순으로 들어가 있는데 (원본 코드도 extra_id_0을 꺼내고 sentinel이 하나씩 늘어날 때마다 index를 하나씩 줄이면서 꺼내는 방식으로 되어 있습니다.) 여기에 제가 ul2를 위한 <r_denoiser_token> <s_denoiser_token> <x_denoiser_token>을 추가하면 103,104,105 번을 순서대로 부여받습니다. 

현재 lassl의 디자인 패턴을 유지하면서 논문에 나온 best mixture of denoisers를 구현하려면 processor에서 1007개씩 토큰을 잘라서 사용하게 되는데요. denoiser 중에 하나인 50% 마스킹, mean_span_length 3을 구현하려면 1007*0.5//3 = 167 개의 sentinel token이 필요합니다. 그래서 기존 T5 tokenizer에 추가해서 <extra_id_100> ~ <extra_id_166>이 추가되어야 합니다. 그런데 위에서 설명드린 것처럼 100번부터 166번이 0번 뒤쪽에 붙게 되기 때문에 collator에서 100개 이상의 sentinel이 사용되는 경우에 대한 예외처리가 들어가야 합니다. (i.e. 100번 이상인 경우 100번째를 찾아서 한개씩 인덱스 늘리기)

T5 collate 함수를 그대로 사용하는 방식은 `train_tokenizers.py` 에 `train_new_from_iterator` 대신에 `train_from_iterator`를 사용하는 방법이 있습니다. 사실 UL2를 제외한 기존 모델들은 `train_new_from_iterator`로도 잘 작동하기 때문에 바꿀 필요는 없어보이고 UL2에 대해서만 스크래치부터 SentencePiece Tokenizer를 학습하도록 예외처리 할 수 있을 것 같습니다. 

위의 두 가지 예외 처리 방식 중에 어떤게 더 낫다고 생각하시나요?

**Comment by DaehanKim** [comment]
위 이슈 부분은 google/ul2 토크나이저가 있어서 그냥 그걸로 받아서 기존 파이프라인 태우는 것으로 진행하고자 합니다. 제가 기존 코드를 자세히 살펴보지 못했네요. 이슈는 닫아도 될 것 같습니다.

**Comment by DaehanKim** [comment]
UL2 Processor 및 Collator 추가
