### ISSUE TITLE
중간에 학습이 끊어졌을 때 이어서 학습하는 feature

### ISSUE THREAD

**Issue by DaehanKim** [lassl/lassl#99]
같은 게 있으면 좋을 것 같습니다. UL2가 알수 없는 이유로 crash 됐는데(w/ GCP 디스크 언마운트) 처음부터 재학습하기에는 이미 들어간 시간이 너무 많아서 체크포인트를 재활용하고 싶은데 어떻게 하면 될까요?

**Comment by seopbo** [comment]
기존 config을 그대로 유지하면서 돌릴 때, 명시된 `output_dir` path에 학습된 checkpoint가 존재하면 그대로 읽어서 resume을 수행합니다.

https://github.com/lassl/lassl/blob/02530e7069cf2a267ee7acdfcb50dc80c6300e90/pretrain_language_model.py#L73-L93

cc: @DaehanKim

**Comment by DaehanKim** [comment]
감사합니다!
